.github/pull_request_template.md, .github/workflows/dev-check-repository.yml, README.md, jest.config.js, package.json
- Add explication in README file
- Add .github folder
MED-125 : https://entsupport.gdapublic.fr/browse/MED-125
=> feat() : [MED-125] Add precisions for conf parameters and .github folder

src/main/resources/public/template/home.html
Fix error  in limit for displaying all resources of home page
MED-133 : https://entsupport.gdapublic.fr/browse/MED-133
=> fix(): [MED-133] Fix limit displaying of signets, resources etc. on home page

src/main/resources/public/ts/controllers/signet.ts
Organisation des signets de chaque utilisateur, dans l'onglet signet, en fonction de sa date de modification (de la plus récente à la plus ancienne).
Les signets sont dans le bon ordre
Lors de la modification, l'ordre se met à jour
Ticket MED-118
https://jira.support-ent.fr/browse/MED-118
=> feat(signet): [MED-118] Organizing favorite signets according to modifying dates

src/main/java/fr/openent/mediacentre/controller/MediacentreController.java
We add an API endpoint to access the config of the module.
This route is only allowed for admins.
Logins and passwords are replaced by '*'.
Issue-10 : https://github.com/OPEN-ENT-NG/ressource-aggregator/issues/10
=> feat(config): [Issue-10] Add routing to get config safely

src/main/java/fr/openent/mediacentre/helper/ElasticSearchHelper.java, src/main/java/fr/openent/mediacentre/helper/elasticsearch/ElasticSearch.java, src/main/java/fr/openent/mediacentre/source/Moodle.java, src/main/java/fr/openent/mediacentre/source/Signet.java
Fix and improve some lines for ES7 use :
- Change import of entcore helper to our own helper
- Delete useless code and query parts
=> feat(ES): [MED] files modified for ES7

.gitignore, build.gradle, build.sh, gradle.properties, jest.config.js, package.json, src/main/resources/public/ts/model/__mocks__/entcore.ts, src/main/resources/public/ts/services/__test__/signet.service.test.ts, src/test/java/fr/openent/mediacentre/i18n/I18nTest.java
- Ajout TU front et back 
- Ajout dépendance build.gradle et package.json
build.gradle
```
"org.powermock".{deps}
"io.vertx:vertx-unit:$vertxVersion"
"org.junit.jupiter:junit-jupiter-engine:$junitVersion"
"org.reflections:reflections:$reflectionsVersion"
"org.mockito:mockito-core:$mockitoVersion"
```
package.json
```
"axios-mock-adapter": "1.21.2",
"@types/jest": "^22.2.0"
```
Les premiers tests incluent : 
- test endpoint API pour jest sur les services
- test lecture json valid
./build.sh test => OK pour tous les tests
=> test: add unit test java and jest angularjs

src/main/resources/public/template/favorite.html, src/main/resources/public/ts/controllers/favorite.ts, src/main/resources/public/ts/controllers/home.ts, src/main/resources/public/ts/controllers/main.ts, src/main/resources/public/ts/controllers/search.ts, src/main/resources/public/ts/controllers/signet.ts, src/main/resources/public/ts/directives/ResourceCard.ts, src/main/resources/public/ts/model/Socket.ts
- refacto home controller
- remove unused calls + websockets
- add calls to favorite service
use favorite header as usual
[MED-174](https://jira.support-ent.fr/browse/MED-174)
=> feat(websocket): MED-174 replace websockets with api call in favorite header

src/main/java/fr/openent/mediacentre/controller/SearchController.java, src/main/java/fr/openent/mediacentre/core/constants/Field.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/template/search.html, src/main/resources/public/ts/controllers/main.ts, src/main/resources/public/ts/controllers/search.ts, src/main/resources/public/ts/directives/ResourceCard.ts, src/main/resources/public/ts/model/searchResponse.ts, src/main/resources/public/ts/services/index.ts, src/main/resources/public/ts/services/search.service.ts
- simple search uses API call instead of websocket
- use simple search tool as usual
[MED-175](https://jira.support-ent.fr/browse/MED-175)
=> feat(websocket): MED-175 replace simple search websockets with api call

src/main/java/fr/openent/mediacentre/controller/SearchController.java, src/main/resources/public/template/advanced-search.html, src/main/resources/public/ts/controllers/main.ts, src/main/resources/public/ts/controllers/search.ts, src/main/resources/public/ts/core/enum/search-type.enum.ts, src/main/resources/public/ts/model/searchBody.model.ts, src/main/resources/public/ts/model/searchData.model.ts
- advanced search uses API call instead of websocket
- use simple search tool as usual
[MED-185](https://jira.support-ent.fr/browse/MED-185)
=> feat(websocket): MED-185 replace advanced search websockets with api call

src/main/java/fr/openent/mediacentre/core/constants/Field.java, src/main/java/fr/openent/mediacentre/core/constants/SourceConstant.java, src/main/java/fr/openent/mediacentre/enums/ErrorEnum.java, src/main/java/fr/openent/mediacentre/enums/SourceEnum.java, src/main/java/fr/openent/mediacentre/helper/ElasticSearchHelper.java, src/main/java/fr/openent/mediacentre/service/FavoriteService.java, src/main/java/fr/openent/mediacentre/service/impl/DefaultFavoriteService.java, src/main/java/fr/openent/mediacentre/source/GAR.java, src/main/resources/public/ts/controllers/home.ts, src/main/resources/public/ts/controllers/main.ts, src/main/resources/public/ts/directives/ResourceCard.ts, src/main/resources/public/ts/model/resource.model.ts, src/main/resources/public/ts/model/resourceBody.model.ts
fixes:
- add and delete external resource favorites
- "Display all" on external resources
use module as usual
[MED-188](https://jira.support-ent.fr/browse/MED-188)
=> feat(external resources): MED-188 fix external resources

src/main/resources/public/template/signets/lightbox/create-signet.html, src/main/resources/public/ts/controllers/signet.ts, src/main/resources/public/ts/controllers/signets/createSignet.ts, src/main/resources/public/ts/model/Label.ts
signet creation works again
try to create a signet and check its form
[MED-189](https://jira.support-ent.fr/browse/MED-189)
=> fix(signet): MED-189 fix signet creation

src/main/resources/public/ts/directives/ResourceCard.ts
favorite indicator becomes yellow when resource is put as favorite
put a moodle item as favorite, check if it works, then delete its favorite (from research)
[MED-193](https://jira.support-ent.fr/browse/MED-193)
=> fix(favorite): MED-196 update research favorite front

src/main/resources/public/template/components/toaster.html, src/main/resources/public/template/signet.html, src/main/resources/public/template/signets/lightbox/prop-signet.html, src/main/resources/public/template/signets/lightbox/publish-signet.html, src/main/resources/public/ts/controllers/main.ts, src/main/resources/public/ts/controllers/signet.ts, src/main/resources/public/ts/controllers/signets/propSignet.ts, src/main/resources/public/ts/controllers/signets/publishSignet.ts, src/main/resources/public/ts/model/signetBody.model.ts, src/main/resources/public/ts/services/signet.service.ts
the following features work again:
- "toaster" button bar (all buttons appear)
- publish button + form
- properties button + form
- sharing form
Use the previously noted features as usual
[MED-194](https://jira.support-ent.fr/browse/MED-194)
=> fix(signet): MED-194 fix signets action buttons

src/main/resources/public/template/signet.html
update date appears
check update date
[MED-198](https://jira.support-ent.fr/browse/MED-198)
=> fix(signet): MED-198 display signet update date

src/main/resources/public/ts/controllers/home.ts, src/main/resources/public/ts/model/signetBody.model.ts, src/main/resources/public/ts/services/signet.service.ts
On home page, displayed signets are only published signets and signets shared with me
check signets displayed on home page
[MED-195](https://jira.support-ent.fr/browse/MED-195)
=> fix(signet): MED-195 display published signets on home page

src/main/resources/public/ts/controllers/home.ts, src/main/resources/public/ts/core/enum/signetType.enum.ts, src/main/resources/public/ts/model/publicSignetResponse.model.ts, src/main/resources/public/ts/model/signetBody.model.ts, src/main/resources/public/ts/services/signet.service.ts
display signets shared with me on homepage
check if shared signets appear
[MED-200](https://jira.support-ent.fr/browse/MED-200)
=> fix(signet): MED-200 display shared signets on home page

src/main/resources/public/ts/controllers/signet.ts
archived signets can be deleted
create signet, archive it
in archive section, select your signet and click on 'delete' --> it should disappear from the platform
[MED-199](https://jira.support-ent.fr/browse/MED-199)
=> fix(delete): MED-199 fix archive deletion

src/main/resources/public/ts/services/favorite.service.ts, src/main/resources/public/ts/services/search.service.ts, src/main/resources/public/ts/services/textbook.service.ts
handle errors when there are no results for a resource type
connect to an account with no favorites --> no warning should pop
to test external resources set gar config "demo" to false
to test signets ask dev
to test textbooks ask dev
[MED-201](https://jira.support-ent.fr/browse/MED-201)
=> fix(service): MED-201 handle empty API response

src/main/java/fr/openent/mediacentre/source/GAR.java
For each structure the user makes a future. Since we were doing a CompositeFuture.join, this would cause data recovery to fail as soon as a structure failed.
Try the simple search, move forward, then click the refresh button on the home page.
=> fix(gar): #MED-206 fix composite future fail when one fail

src/main/resources/public/ts/controllers/home.ts
Change API called by refresh button
MED-187 : https://jira.support-ent.fr/browse/MED-187
=> fix(resync): [#MED-187] fix refresh button on home page

src/main/java/fr/openent/mediacentre/controller/MediacentreController.java, src/main/java/fr/openent/mediacentre/controller/SignetController.java, src/main/java/fr/openent/mediacentre/core/constants/Field.java, src/main/java/fr/openent/mediacentre/model/SignetResource.java, src/main/java/fr/openent/mediacentre/service/SignetService.java, src/main/java/fr/openent/mediacentre/service/impl/DefaultSignetService.java, src/main/java/fr/openent/mediacentre/source/GAR.java, src/test/java/fr/openent/mediacentre/service/test/impl/DefaultSignetServiceTest.java
Add a Mediacentre widget.
This which display the 4 firsts favorites resources of the user (either GAR resources or Signets).
It also includes the Universalis widget if the user has this specific resource
Documentation API : https://confluence.support-ent.fr/display/MED/Signet
MED-214 : https://jira.support-ent.fr/browse/MED-214
=> feat(mediacentre-widget): [#MED-214] add routes for mediacentre-widget

src/main/java/fr/openent/mediacentre/controller/FavoriteController.java, src/main/java/fr/openent/mediacentre/controller/GlobalResourceController.java, src/main/java/fr/openent/mediacentre/controller/MediacentreController.java, src/main/java/fr/openent/mediacentre/core/constants/Field.java, src/main/java/fr/openent/mediacentre/helper/FutureHelper.java, src/main/java/fr/openent/mediacentre/helper/IModelHelper.java, src/main/java/fr/openent/mediacentre/service/FavoriteService.java, src/main/java/fr/openent/mediacentre/service/GlobalResourceService.java, src/main/java/fr/openent/mediacentre/service/impl/DefaultFavoriteService.java, src/main/java/fr/openent/mediacentre/service/impl/GlobalResourceServiceMongoImpl.java, src/main/resources/public/sass/global/_mediacentre-specifics.scss, src/main/resources/public/sass/global/components/_header.scss, src/main/resources/public/ts/controllers/signet.ts, src/main/resources/public/ts/services/favorite.service.ts, src/main/resources/view-src/mediacentre.html, src/test/java/fr/openent/mediacentre/service/test/impl/GlobalResourceTest.java
Fix favorites behaviours in homepage
MED-227 : https://jira.support-ent.fr/browse/MED-227
=> fix(favorites): [#MED-227] fix favorites behaviours in homepage

src/main/resources/public/ts/controllers/home.ts
Fix sync external resources
MED-230 : https://jira.support-ent.fr/browse/MED-230
=> fix(externalResources): [#MED-230] fix sync external resources

src/main/java/fr/openent/mediacentre/core/constants/Field.java, src/main/java/fr/openent/mediacentre/core/constants/SourceConstant.java, src/main/java/fr/openent/mediacentre/enums/SourceEnum.java, src/main/java/fr/openent/mediacentre/model/GarResource.java, src/main/java/fr/openent/mediacentre/model/GlobalResource.java, src/main/java/fr/openent/mediacentre/model/Resource.java, src/main/java/fr/openent/mediacentre/service/impl/DefaultFavoriteService.java, src/main/java/fr/openent/mediacentre/service/impl/GlobalResourceServiceMongoImpl.java, src/main/resources/public/ts/controllers/home.ts, src/main/resources/public/ts/core/enum/sources.enum.ts, src/main/resources/public/ts/directives/ResourceCard.ts, src/main/resources/public/ts/model/resourceBody.model.ts
Global resources are common to all the users using it. We had to adapt logic to allow users to put these resources in their favorites without impacting other users. To do it we use the "id" property, like it's done for the Signet type resources
MED-227 : https://jira.support-ent.fr/browse/MED-227
=> fix(favorites): [#MED-227] fix favorites behaviours for global resources

src/main/resources/public/sass/global/components/_dominos.scss, src/main/resources/public/ts/controllers/signets/propSignet.ts, src/main/resources/public/ts/controllers/signets/publishSignet.ts
Fix some errors in signet :
- text color
- display of prop lightbox
- display of publish lightbox
MED-232 : https://jira.support-ent.fr/browse/MED-232
=> fix(signet): [#MED-232] fix signet lightbox and text color

frontend/src/components/resource/Resource.tsx, frontend/src/dictionaries/en.json, frontend/src/dictionaries/fr.json, frontend/src/hooks/useFavorite.ts, frontend/src/hooks/useSignet.ts, frontend/src/hooks/useTextbook.ts, frontend/src/model/Resource.model.ts, frontend/src/model/Signet.model.ts, frontend/src/routes/app/index.tsx, frontend/src/services/api/favorite.service.ts
We can add or remove favorite resource
- Check if you can add favorite in textbooks and signets
- Check if you can remove favorite in textbooks and signets
[https://jira.support-ent.fr/browse/MED-239](MED-239)
=> feat(favorite): #MED-239 add or remove favorite

angularJS/src/template/header.html, backend/src/main/java/fr/openent/mediacentre/controller/MediacentreController.java, frontend/src/components/sidebar/Sidebar.scss, frontend/src/components/sidebar/Sidebar.tsx
Make redirection react/angular to use the module in hybride.
Link the sidebar.
Navigation with different click on angular and react pages.
[MED-279](https://jira.support-ent.fr/browse/MED-279)
=> feat(sidebar): #MED-279 redirection react/angular

frontend/src/dictionaries/en.json, frontend/src/dictionaries/fr.json, frontend/src/routes/search/index.tsx
Add a infinite scroll in search page
- Check we can load more data then 10
[MED-280](https://jira.support-ent.fr/browse/MED-280)
=> feat(infinite scroll): #MED-280 add infinite scroll search page

frontend/src/components/resource/Resource.tsx, frontend/src/components/search-card/SearchCard.tsx, frontend/src/dictionaries/en.json, frontend/src/dictionaries/fr.json
Display tooltips on card buttons
check the display of tooltip of each buttons and for home cards and search cards
[MED-278](https://jira.support-ent.fr/browse/MED-278)
=> feat(tooltip): #MED-278 make tooltip for card buttons

build.sh, frontend/src/components/resource/Resource.tsx, frontend/src/routes/app/index.tsx
We have a infinite loop in load image because image is not import, its done now
- Check if have "no-avatar.svg" image
[MED-261](https://jira.support-ent.fr/browse/MED-261)
=> fix(image): #MED-261 fix bug image

frontend/src/components/filter-layout/FilterLayout.tsx, frontend/src/components/search-card/SearchCard.tsx, frontend/src/components/sidebar/Sidebar.tsx, frontend/src/hooks/useSignet.ts, frontend/src/model/Signet.model.ts, frontend/src/routes/index.tsx, frontend/src/routes/resources/index.tsx, frontend/src/routes/textbook/index.tsx
Add a textbook and resources, separate of search page
- Check if we have resources in both pages and we can filters they
[MED-248](https://jira.support-ent.fr/browse/MED-248)
=> feat(textbook/resources): #MED-248 add textbook and resources page

frontend/src/components/list-card/ListCard.scss, frontend/src/components/list-card/ListCard.tsx, frontend/src/main.tsx, frontend/src/routes/app/index.tsx
Home page can redirect in each category
-> Check if you are redirect at good place
[MED-266](https://jira.support-ent.fr/browse/MED-266)
=> feat(redirect): #MED-266 redirect each category

backend/src/main/java/fr/openent/mediacentre/controller/MediacentreController.java, backend/src/main/java/fr/openent/mediacentre/core/constants/Field.java, backend/src/main/java/fr/openent/mediacentre/helper/IModelHelper.java, backend/src/main/java/fr/openent/mediacentre/model/Resource.java
When we get resources from GAR and use models to format, some are not well managed.
Specially the fields of :
- List<String>
- Date
One example of this is Universalis resource wich were not possible to format.
- You need Unievrsalis in the retrieve data from GAR for this (either fake or not)
- Log in with an account having Mediacentre widget
- Go on the Timeline
- You should see an Unievrsalis search bar at the bottom of the widget
FOR-283 : https://jira.support-ent.fr/browse/MED-283
=> fix(GAR): [#MED-283] fix model back to adapt to resources like Universalis

frontend/.husky/pre-commit, frontend/src/components/resource/Resource.tsx, frontend/src/components/search-card/SearchCard.tsx, frontend/src/hooks/useSearch.ts, frontend/src/model/SearchResource.model.ts, frontend/src/routes/app/index.tsx, frontend/src/routes/resources/index.tsx, frontend/src/routes/search/index.tsx, frontend/src/routes/textbook/index.tsx
Pins icons removed
Textbook page & resources pages added
- Check if pin are removed
- Check if we can access to textbook & resource pages
[MED-250](https://jira.support-ent.fr/browse/MED-250)
=> feat(icons): #MED-250 remove pin icon and add textbook & resource pages

frontend/src/components/resource/Resource.tsx, frontend/src/components/search-card/SearchCard.tsx
Fix tooltip placement right to top
Check that the tooltip is at the top
[MED-278](https://jira.support-ent.fr/browse/MED-278)
=> fix(tooltip): #MED-278 fix tooltip placement

angularJS/src/template/header.html, angularJS/src/ts/controllers/main.ts, frontend/src/components/header/Header.tsx, frontend/src/routes/index.tsx, frontend/src/routes/search/index.tsx
change search query and redirect angular search to react search
check the redirection 
[MED-282](https://jira.support-ent.fr/browse/MED-282)
=> feat(redirection) make redirection angular search to react search

frontend/src/components/header/Header.tsx
fix search bug
check that changement fix the bug
[MED-282](https://jira.support-ent.fr/browse/MED-282)
=> fix(search): #MED-282 fix search bug

frontend/src/components/resource/Resource.tsx, frontend/src/components/search-card/SearchCard.tsx, frontend/src/hooks/useSearch.ts, frontend/src/routes/resources/index.tsx, frontend/src/routes/textbook/index.tsx
fix empty data
[MED-239](https://jira.support-ent.fr/browse/MED-239)
=> fix(search): #MED-239 fix empty data

frontend/src/core/const/home-element-list-sizes.const.ts, frontend/src/routes/app/index.tsx
Delete pinned bloc on home page
display of other blocs without pinned one 
check the responsive
[MED-273](https://jira.support-ent.fr/browse/MED-273)
=> fix(home page): #MED-273 delete pinned bloc

frontend/src/components/resource/Resource.tsx, frontend/src/components/search-card/SearchCard.tsx, frontend/src/model/Resource.model.ts, frontend/src/model/SearchResource.model.ts, frontend/src/routes/app/index.tsx, frontend/src/services/api/favorite.service.ts
Fix the model of favorite
- Check if we can add or remove favorite
[MED-267](https://jira.support-ent.fr/browse/MED-267)
=> fix(search): #MED-267: fix add or remove favorite

frontend/src/components/resource/Resource.tsx, frontend/src/hooks/useSignet.ts, frontend/src/model/Signet.model.ts, frontend/src/routes/app/index.tsx
Do not display the creator name of a shared bookmark
- Check if shared bookmark is "Signet de la plateforme"
[MED-241](https://jira.support-ent.fr/browse/MED-241)
=> fix(signets): #MED-241 fix signets footer

backend/src/main/java/fr/openent/mediacentre/controller/SearchController.java, backend/src/main/java/fr/openent/mediacentre/source/GAR.java, frontend/src/components/header/Header.tsx
Fix search with gar demo
- Check if search works
[MED-236](https://jira.support-ent.fr/browse/MED-236)
=> fix(search): #MED-236 fix search for demo

frontend/src/routes/resources/index.tsx, frontend/src/routes/search/index.tsx, frontend/src/routes/textbook/index.tsx
Filters are not loadead, its done now
- Check if filters works
[MED-276](https://jira.support-ent.fr/browse/MED-276)
=> fix(filters): #MED-276 fix filters

frontend/src/components/filter-layout/FilterLayout.scss, frontend/src/components/filter-layout/FilterLayout.tsx, frontend/src/components/header/Header.scss, frontend/src/components/header/Header.tsx, frontend/src/components/resource/Resource.scss, frontend/src/components/resource/Resource.tsx, frontend/src/components/search-card/SearchCard.tsx, frontend/src/components/sidebar-icon/SidebarIcon.scss, frontend/src/core/const/list-titles.const.ts, frontend/src/core/const/search-card-title.const.ts, frontend/src/core/enum/card-type.enum.ts, frontend/src/routes/resources/index.tsx, frontend/src/routes/textbook/index.tsx, frontend/src/styles/page/home.scss, frontend/src/styles/page/search.scss
Fix global css
[MED-284](https://jira.support-ent.fr/browse/MED-284)
=> fix(css): #MED-284 fix css

frontend/src/components/header/Header.tsx
Fix redirection on mediacentre home page when we clic on mediacentre title (header)
Check the redirection on different pages of mediacentre
[MED-246](https://jira.support-ent.fr/browse/MED-246)
=> fix(redirect home): #MED-246 fix redirection home on title page clic

frontend/src/components/home-lists/HomeExternalResourcesList.tsx, frontend/src/components/resource/Resource.tsx, frontend/src/components/search-card/SearchCard.tsx, frontend/src/core/const/list-titles.const.ts, frontend/src/hooks/useGlobal.ts, frontend/src/model/GlobalResource.ts, frontend/src/routes/app/index.tsx, frontend/src/routes/resources/index.tsx, frontend/src/services/api/global.service.ts, frontend/src/styles/page/home.scss
A parent have global resources in home page and resources page
- Connect with parent account and check have global resources
[MED-287](https://jira.support-ent.fr/browse/MED-287)
=> feat(globalResource): #MED-287 add global resources

frontend/src/components/resource/Resource.tsx, frontend/src/components/search-card/SearchCard.tsx, frontend/src/hooks/useSearch.ts, frontend/src/services/api/favorite.service.ts
Fix favorite with GAR ressources
- Check if we can add favorite
[MED-239](https://jira.support-ent.fr/browse/MED-239)
=> fix(favorite): #MED-239 fix favorite

frontend/src/components/sidebar/Sidebar.tsx
change redirection method in order to refresh the page on redirection
* check redirection ok
* check refresh ok
[MED-248](https://jira.support-ent.fr/browse/MED-248)
=> fix(sidebar): #MED-248 fix home redirection

frontend/src/components/filter-layout/FilterLayout.tsx, frontend/src/components/filter-textbook-layout/FilterTextbookLayout.tsx, frontend/src/components/resource/Resource.tsx, frontend/src/components/search-card/SearchCard.tsx, frontend/src/hooks/useExternalResource.ts, frontend/src/hooks/useFavorite.ts, frontend/src/hooks/useSearch.ts, frontend/src/hooks/useTextbook.ts, frontend/src/main.tsx, frontend/src/model/Textbook.model.ts, frontend/src/routes/app/index.tsx, frontend/src/routes/resources/index.tsx, frontend/src/routes/search/index.tsx, frontend/src/routes/textbook/index.tsx, frontend/src/routes/user/index.tsx, frontend/src/services/api/index.ts
Fix a favorite bug with textbook
- Check if we can add favorite in textbooks
[MED-244](https://jira.support-ent.fr/browse/MED-244)
=> fix(textbooks): #MED-244 fix favorite with textbooks on rerender

frontend/src/routes/resources/index.tsx, frontend/src/routes/textbook/index.tsx
Fix fetch favorite when add favorite in textbook page and dont displayed in resource page
- Add favorite in textbooks page, and see if added in resource page
[MED-239](https://jira.support-ent.fr/browse/MED-239)
=> fix(favorite): #MED-239 fix fetch favorite

frontend/src/components/header/Header.scss, frontend/src/routes/resources/index.tsx, frontend/src/routes/textbook/index.tsx, frontend/src/styles/page/search.scss
Favorite resources are re-loaded when we change page
- Check if favorite are loaded when page change
[MED-239](https://jira.support-ent.fr/browse/MED-239)
=> fix(favorite): #MED-239 fix favorite refresh data & scss

frontend/src/components/filter-layout/FilterLayout.tsx
When we reload search page, filters are not reload, its done now
- Check if when we reload search page, filters are updated
[MED-276](https://jira.support-ent.fr/browse/MED-276)
=> fix(filters): #MED-276 fix filters reload page

frontend/src/routes/resources/index.tsx, frontend/src/routes/search/index.tsx, frontend/src/routes/textbook/index.tsx
Fix scroll infinite when we use filters in all search page
- Check if scroll infinite works
[MED-280](https://jira.support-ent.fr/browse/MED-280)
=> fix(scroll): #MED-280 fix scroll when filters updated

backend/src/main/java/fr/openent/mediacentre/core/constants/Field.java, backend/src/main/java/fr/openent/mediacentre/model/GarResource.java, backend/src/main/java/fr/openent/mediacentre/source/GAR.java, frontend/src/components/resource/Resource.tsx, frontend/src/components/resource/resource-title/ResourceTitle.scss, frontend/src/components/resource/resource-title/ResourceTitle.tsx, frontend/src/components/search-card/SearchCard.tsx, frontend/src/model/Favorite.model.ts, frontend/src/model/SearchResource.model.ts, frontend/src/model/Textbook.model.ts
add field is_textbook=true for textbooks to differentiate them from external_resources
add icon for favorite cards
check json result for different request
check the display of icon (allow to differentiate manuals from external resources)
[MED-220](https://jira.support-ent.fr/browse/MED-220)
=> feat(favorites): #MED-288 add the differentiation between manuals and external_resources

frontend/src/components/filter-layout/FilterLayout.tsx, frontend/src/components/home-lists/HomeList.tsx, frontend/src/components/infinite-scroll-list/InfiniteScrollList.tsx, frontend/src/components/sidebar/Sidebar.tsx, frontend/src/routes/app/index.tsx, frontend/src/routes/favorites/index.tsx, frontend/src/routes/index.tsx, frontend/src/routes/resources/index.tsx, frontend/src/routes/search/index.tsx, frontend/src/routes/textbook/index.tsx
Add favorite page and redirect favorite page on this new page and not on angular page
Check the filter, check the redirection
[MED-249](https://jira.support-ent.fr/browse/MED-249)
=> feat(favorite page): #MED-249 add favorite page

frontend/src/components/search-card/SearchCard.tsx
During the refactoring, the name of a function was not changed, which caused a bug in the refresh process that needs to occur when adding and removing a favorite.
check the bug is resolved
[MED-249](https://jira.support-ent.fr/browse/MED-249)
=> fix(favorites): #MED-249 fix star icon display on fav/unfav

frontend/src/components/resource/resource-title/ResourceTitle.scss, frontend/src/components/resource/resource-title/ResourceTitle.tsx, frontend/src/components/search-card/search-card-type/SearchCardType.tsx
fix favorite icon display for home page
check the display of different types of favorite
[MED-288](https://jira.support-ent.fr/browse/MED-288)
=> fix(fav icon): #MED-288 fix home favorite icons

frontend/src/components/home-lists/HomeList.tsx, frontend/src/components/infinite-scroll-list/InfiniteScrollList.tsx, frontend/src/components/modals/Modal.scss, frontend/src/components/modals/confirm-delete/ConfirmDelete.tsx, frontend/src/components/modals/create-pins/CreatePins.tsx, frontend/src/components/modals/edit-pins/EditPins.tsx, frontend/src/components/pins-carousel/PinsCarousel.scss, frontend/src/components/pins-carousel/PinsCarousel.tsx, frontend/src/components/pins-carousel/pins-carousel-card/PinsCarouselCard.scss, frontend/src/components/pins-carousel/pins-carousel-card/PinsCarouselCard.tsx, frontend/src/components/resource/Resource.tsx, frontend/src/components/search-card/SearchCard.tsx, frontend/src/dictionaries/en.json, frontend/src/dictionaries/fr.json, frontend/src/hooks/usePin.ts, frontend/src/main.tsx, frontend/src/model/Pin.model.ts, frontend/src/providers/AlertProvider.tsx, frontend/src/providers/ModalsProvider.tsx, frontend/src/providers/types.ts, frontend/src/routes/app/index.tsx, frontend/src/routes/resources/index.tsx, frontend/src/routes/search/index.tsx, frontend/src/routes/textbook/index.tsx, frontend/src/services/api/pin.service.ts, frontend/src/styles/_colors.scss
Add 3 modals for create, delete or update a pin resource.
- Check if we can use 3 modals
=> feat(modals): #MED-310 add modals to create, edit and delete pin resource

frontend/src/hooks/useGlobal.ts, frontend/src/hooks/useTextbook.ts
fix NPE on pins 
[MED-297](https://jira.support-ent.fr/browse/MED-297)
=> fix(icon-pins): #MED-297 fix npe on pins

frontend/src/components/modals/create-pins/CreatePins.tsx
fix creation of a favorite pin
=> fix(create pin): #MED-310 fix creation of a favorite pin

frontend/src/components/pins-carousel/pins-carousel-card/PinsCarouselCard.tsx, frontend/src/routes/app/index.tsx
fix manage pin with tree structure
=> fix(manage pin): #MED-310 fix manage pin with tree structure

frontend/src/components/filter-layout/FilterLayout.tsx, frontend/src/components/infinite-scroll-list/InfiniteScrollList.tsx, frontend/src/components/search-card/SearchCard.tsx, frontend/src/hooks/useSearch.ts, frontend/src/routes/favorites/index.tsx, frontend/src/routes/resources/index.tsx, frontend/src/routes/search/index.tsx, frontend/src/routes/textbook/index.tsx, frontend/src/utils/sortResources.util.ts
fix bugs on infinite scroll
[MED-309](https://jira.support-ent.fr/browse/MED-309)
=> fix(infinite-scroll): #MED-309 fix infinite scroll and add sort of data

backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultPinsService.java, frontend/src/components/modals/create-pins/CreatePins.tsx, frontend/src/components/modals/edit-pins/EditPins.tsx
Block spaces before the title and description of a pin when creating or editing it. 
Allow setting the description to "" (empty).
check that it work (on ng2)
=> fix(pins): #MED-310 fix pin create and edit

frontend/src/components/pins-carousel/pins-carousel-card/PinsCarouselCard.tsx
=> fix(pins): #MED-310 remove offered by the region

frontend/src/components/filter-layout/FilterLayout.tsx, frontend/src/components/sidebar/Sidebar.tsx, frontend/src/dictionaries/en.json, frontend/src/dictionaries/fr.json, frontend/src/routes/index.tsx, frontend/src/routes/signets/index.tsx
create Signet Page and redirect sidebar to this page
check the redirection and the display
[MED-256](https://jira.support-ent.fr/browse/MED-256)
=> feat(signet page): #MED-256 create signet page

frontend/src/components/admin-signet/AdminSignet.scss, frontend/src/components/admin-signet/AdminSignet.tsx, frontend/src/components/infinite-scroll-list/InfiniteScrollList.tsx, frontend/src/dictionaries/en.json, frontend/src/dictionaries/fr.json, frontend/src/routes/signets/index.tsx, frontend/src/styles/_colors.scss, frontend/src/styles/page/signet.scss
Add a design for admin and give access to this page only admins signets users
- Check when you have manage signet right, you have access to admin page
- Check when you dont have this right, its normal signet page
[MED-300](https://jira.support-ent.fr/browse/MED-300)
=> feat(signet-admin): #MED-300 add admin page & design

frontend/src/components/modals/confirm-delete/ConfirmDelete.tsx, frontend/src/components/modals/create-signet/CreateSignet.tsx, frontend/src/components/pins-carousel/pins-carousel-card/PinsCarouselCard.tsx, frontend/src/hooks/useExternalResource.ts, frontend/src/hooks/useSearch.ts, frontend/src/hooks/useTextbook.ts, frontend/src/providers/PinProvider.tsx
refetch data after change structure
[MED-242](https://jira.support-ent.fr/browse/MED-242)
=> fix(multi-structures): #MED-242 refetch data after change structure

frontend/src/hooks/useSignet.ts, frontend/src/providers/PinProvider.tsx
=> fix(feedback): #MED-325 fix bugs on signets

frontend/src/components/filter-layout/utils.ts
=> fix(feedback): #MED-325 fix filters

frontend/src/components/filter-layout/utils.ts, frontend/src/hooks/useSignet.ts, frontend/src/model/Resource.model.ts, frontend/src/utils/property.utils.ts
=> fix(feedback): #MED-325 fix filters for signets

frontend/src/components/infinite-scroll-list/InfiniteScrollList.tsx, frontend/src/components/search-card/search-card-subtitle/SearchCardSubtitle.tsx, frontend/src/dictionaries/en.json, frontend/src/dictionaries/fr.json, frontend/src/hooks/useSignet.ts
=> feat(feedback): #MED-325 fix signet display bugs

frontend/src/components/filter-layout/FilterLayout.tsx, frontend/src/components/filter-layout/utils.ts, frontend/src/components/search-card/search-card-subtitle/SearchCardSubtitle.tsx, frontend/src/hooks/useResourceListInfo.ts, frontend/src/model/ResourcesMap.ts, frontend/src/model/SearchResource.model.ts, frontend/src/routes/app/index.tsx, frontend/src/routes/resources/index.tsx
Now, global resources are displayed.
- Check if we see global resources
[https://jira.support-ent.fr/browse/MED-330](https://jira.support-ent.fr/browse/MED-330)
=> fix(global): #MED-330 fix global resources

frontend/src/components/admin-signet/AdminSignet.scss
Fix css admin signet page
- Check if title have correct font weight
[MED-302](https://jira.support-ent.fr/browse/MED-302)
=> fix(css): #MED-302 fix css admin signet page

backend/src/main/resources/i18n/en.json, backend/src/main/resources/i18n/fr.json
Update i18n
- Check if i18n is correct
[MED-338](https://jira.support-ent.fr/browse/MED-338)
=> fix(i18n): #MED-338 fix i18n

frontend/src/components/empty-state/EmptyState.scss
Fix empty state size
- Check empty state size
[MED-316](https://jira.support-ent.fr/browse/MED-316)
=> fix(empty-state): #MED-316 fix empty state size

frontend/src/components/drop-down/DropDown.tsx, frontend/src/components/modals/create-signet/CreateSignet.tsx
Change dropdown choice for create signet modal
- Check if we can select all and deselect all in create signet modal
[MED-301](https://jira.support-ent.fr/browse/MED-301)
=> fix(filter): #MED-301 fix dropdown for create signet

frontend/src/components/admin-signet/AdminSignet.tsx, frontend/src/components/modals/signet-publish/SignetPublish.tsx, frontend/src/hooks/useSignet.ts, frontend/src/routes/signets/index.tsx
Refetch resources when change page selected
- Check if resources are correctly deleted
[MED-332](https://jira.support-ent.fr/browse/MED-)
=> fix(refetch): #MED-332 signet need update to refetch data

frontend/src/hooks/useSignet.ts
Fix a bug with linked favorite public and private signet
- Add favorite in private signet and see if same public signet is favorite too
[MED-115](https://jira.support-ent.fr/browse/MED-115)
=> fix(favorite): #MED-115 fix linked public and private signet favorite

backend/src/main/java/fr/openent/mediacentre/controller/GlobalResourceController.java, backend/src/main/java/fr/openent/mediacentre/helper/IModelHelper.java, backend/src/main/java/fr/openent/mediacentre/helper/StringHelper.java, backend/src/main/java/fr/openent/mediacentre/model/GlobalResource.java, backend/src/main/java/fr/openent/mediacentre/service/GlobalResourceService.java, backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultGlobalResourceService.java, backend/src/test/java/fr/openent/mediacentre/service/test/impl/GlobalResourceTest.java, frontend/src/components/resource/Resource.tsx, frontend/src/components/resource/resource-title/ResourceTitle.tsx, frontend/src/components/search-card/SearchCard.tsx, frontend/src/hooks/useGlobal.ts, frontend/src/hooks/useSignet.ts, frontend/src/routes/app/index.tsx, frontend/src/routes/favorites/index.tsx
Now we can add a favorite global resource and manage them
- Add/Remove favorite global resource
[MED-275](https://jira.support-ent.fr/browse/MED-275)
=> feat(global): #MED-275 add favorite global resource

backend/src/main/java/fr/openent/mediacentre/Mediacentre.java, backend/src/main/java/fr/openent/mediacentre/controller/FavoriteController.java, backend/src/main/java/fr/openent/mediacentre/helper/FavoriteHelper.java, backend/src/main/java/fr/openent/mediacentre/helper/TextBookHelper.java, backend/src/main/java/fr/openent/mediacentre/service/TextBookService.java, backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultTextBookService.java, frontend/.eslintrc.cjs, frontend/src/routes/signets/index.tsx
Old favorites are still visible even if the resource no longer exists, now these resources are hidden
- Check if favorites are correctly displayed
[MED-155](https://jira.support-ent.fr/browse/MED-155)
=> fix(favorite): #MED-155 favorites are displayed only if resource exist

backend/src/main/java/fr/openent/mediacentre/controller/SignetController.java, backend/src/main/java/fr/openent/mediacentre/core/constants/Field.java, backend/src/main/java/fr/openent/mediacentre/service/SignetService.java, backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultSignetService.java
We need to created a shared array for all signets to manage them
- Check if signet have shared property
[MED-334](https://jira.support-ent.fr/browse/MED-334)
=> fix(share): #MED-334 create shared array for all signets

.gitignore, JenkinsFile, README.md, backend/src/main/java/fr/openent/mediacentre/Mediacentre.java, backend/src/main/java/fr/openent/mediacentre/controller/MediacentreController.java, backend/src/main/java/fr/openent/mediacentre/controller/PinsController.java, backend/src/main/java/fr/openent/mediacentre/core/constants/Field.java, backend/src/main/java/fr/openent/mediacentre/helper/FutureHelper.java, backend/src/main/java/fr/openent/mediacentre/helper/TextBookHelper.java, backend/src/main/java/fr/openent/mediacentre/service/NotifyService.java, backend/src/main/java/fr/openent/mediacentre/service/PinsService.java, backend/src/main/java/fr/openent/mediacentre/service/TextBookService.java, backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultNotifyService.java, backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultPinsService.java, backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultTextBookService.java, backend/src/main/java/fr/openent/mediacentre/source/GAR.java, backend/src/main/resources/i18n/en.json, backend/src/main/resources/i18n/fr.json, backend/src/main/resources/i18n/timeline/en.json, backend/src/main/resources/i18n/timeline/fr.json, backend/src/main/resources/view-src/notify/pinned_resource_notification.html, backend/src/main/resources/view-src/notify/pinned_resource_notification.json, build.sh, frontend/src/components/modals/create-pins/CreatePins.tsx, frontend/src/providers/PinProvider.tsx, frontend/src/providers/types.ts
Add a notification for all users can see the resource when a admin pinned a resource
- Pin a resource and check if received notification
[MED-216](https://jira.support-ent.fr/browse/MED-216)
=> fix(notification): #MED-216 notify users when resource is pinned

frontend/src/components/pins-carousel/pins-carousel-card/PinsCarouselCard.scss, frontend/src/components/pins-carousel/pins-carousel-card/PinsCarouselCard.tsx, frontend/src/hooks/useSignet.ts, frontend/src/providers/PinProvider.tsx
Add favorites to pinned resources, the original resource of the pin is added to favorites
- Check if we can add favorites in pinned resources
[MED-298](https://jira.support-ent.fr/browse/MED-298)
=> fix(favorites): #MED-298 add favorites to pinned resources

frontend/src/components/header/Header.scss, frontend/src/components/pins-carousel/PinsCarousel.scss, frontend/src/components/resource/Resource.scss
Fix some css
- Check if css works good
[MED-351](https://jira.support-ent.fr/browse/MED-351)
=> fix(css): #MED-351 fix some css

backend/deployment/mediacentre/conf.json.template, backend/pom.xml, backend/src/main/java/fr/openent/mediacentre/Mediacentre.java, backend/src/main/java/fr/openent/mediacentre/controller/FeaturedResourcesController.java, backend/src/main/java/fr/openent/mediacentre/core/constants/Field.java, backend/src/main/java/fr/openent/mediacentre/helper/TextBookHelper.java, backend/src/main/java/fr/openent/mediacentre/model/FeaturedResource.java, backend/src/main/java/fr/openent/mediacentre/service/FeaturedResourcesService.java, backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultFeaturedResourcesService.java
Création d'un service qui récupère les ressources mise en avant par la région dans MongoDB, les compares à celles auxquelles l'utilisateur à accès dans le GAR, et renvoie le résultat.
https://jira.support-ent.fr/browse/MED-357
=> feat(featured_resources): #MED-357 create EventBus to send featured GAR resources

.github/pull_request_template.md, backend/src/main/resources/i18n/timeline/en.json, backend/src/main/resources/i18n/timeline/fr.json
[MED-359](https://jira.support-ent.fr/browse/MED-359)
=> feat(): [#MED-359] add i18n for mobile notif

frontend/src/services/api/emptySplitApi.service.ts
[MED-368](https://jira.support-ent.fr/browse/MED-368)
=> fix: #MED-368 infinite loader when error

backend/src/main/java/fr/openent/mediacentre/Mediacentre.java, backend/src/main/java/fr/openent/mediacentre/core/constants/Field.java, backend/src/main/java/fr/openent/mediacentre/service/TextBookService.java, backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultPinsService.java, backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultTextBookService.java, frontend/eslint.config.js, frontend/package.json
This pull request includes several changes to the `backend` module of the `mediacentre` project, focusing on adding new constants, modifying methods for efficiency, and improving the notification system. The most important changes include adding new constants to the `Field` class, updating the `TextBookService` interface, and refactoring the `DefaultPinsService` class for better performance and maintainability.
* [`backend/src/main/java/fr/openent/mediacentre/Mediacentre.java`](diffhunk://#diff-5951c38753b7b3b4c91f9044a8a2d80ef0083e652b2ac9c79a501630d842ca6bR41): Added `MEDIACENTRE_VIEW` constant for the Mediacentre view controller.
* [`backend/src/main/java/fr/openent/mediacentre/core/constants/Field.java`](diffhunk://#diff-94641f0c40fb11c5432bc533f069198294cd588c596e90b1854b22e31ea184ebR …
=> fix(notif): #MED-354 restrict new pin notifs to users with MediaCentre access

backend/src/main/resources/i18n/en.json, backend/src/main/resources/i18n/fr.json, frontend/src/components/pins-carousel/pins-carousel-card/PinsCarouselCard.tsx, frontend/src/components/resource/Resource.tsx, frontend/src/components/search-card/SearchCard.tsx
This pull request introduces several changes to the frontend and backend of the application, focusing on adding a duplication feature for Moodle resources and updating the icons used in various components. The most important changes include adding new translations, implementing a duplication handler, and updating the icons for better visual consistency.
* Added a new translation entry for "Dupliquer" in both `en.json` and `fr.json` files.
* **PinsCarouselCard, Resource, SearchCard Components:**
* Updated import statements to use rounded icons for copy and link actions.
* Added a `handleDuplicate` function to handle duplication of Moodle resources.
* Modified the tooltip logic to display the appropriate message and icon based on the resource type. …
=> feat(moodle): #MED-356 add duplication for moodle resources

backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultNotifyService.java, backend/src/main/resources/i18n/en.json, backend/src/main/resources/i18n/fr.json, backend/src/main/resources/i18n/timeline/en.json, backend/src/main/resources/i18n/timeline/fr.json, frontend/src/components/pins-carousel/pins-carousel-card/PinsCarouselCard.tsx, frontend/src/components/resource/Resource.tsx, frontend/src/components/search-card/SearchCard.tsx
This pull request includes updates to the notification service and localization files to enhance the notification system for pinned resources in the médiacentre.
* [`backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultNotifyService.java`](diffhunk://#diff-2b4ae7c89861adf0056bc900679049ead97992050730eb9b17f743e998f46306R5-L7): Added the `I18n` import and used it to translate the push notification body for new resources. This ensures the notification is localized based on the user's language preference. [[1]](diffhunk://#diff-2b4ae7c89861adf0056bc900679049ead97992050730eb9b17f743e998f46306R5-L7) [[2]](diffhunk://#diff-2b4ae7c89861adf0056bc900679049ead97992050730eb9b17f743e998f46306R51-R64)
* [`backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultNotifyService.java`]( …
=> fix(notif): #MED-371 mobile notif for new pin

backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultNotifyService.java, backend/src/main/java/fr/openent/mediacentre/source/Moodle.java, backend/src/main/resources/i18n/en.json, backend/src/main/resources/i18n/fr.json, backend/src/main/resources/i18n/timeline/en.json, backend/src/main/resources/i18n/timeline/fr.json, frontend/src/components/pins-carousel/pins-carousel-card/PinsCarouselCard.tsx, frontend/src/components/resource/Resource.tsx, frontend/src/components/search-card/SearchCard.tsx
This pull request includes changes to the `Moodle` class in the `backend/src/main/java/fr/openent/mediacentre/source/` directory to enhance the plain text search functionality by adding user profile checks. The most important changes include importing the `Profile` enum and modifying the `plainTextSearch` method to include conditional checks based on the user profile.
Enhancements to plain text search functionality:
* [`backend/src/main/java/fr/openent/mediacentre/source/Moodle.java`](diffhunk://#diff-b15d51f42dea37776780a9233bb45eff80c407e7123a014227fc2369cd254e34R3): Imported the `Profile` enum to the `Moodle` class.
* [`backend/src/main/java/fr/openent/mediacentre/source/Moodle.java`](diffhunk://#diff-b15d51f42dea37776780a9233bb45eff80c407e7123a014227fc2369cd254e34R44-R45): Modified …
=> feat(notif): #MED-373 restrict Moodle resources access to teachers and personnels only

backend/src/main/java/fr/openent/mediacentre/controller/SignetController.java, backend/src/main/java/fr/openent/mediacentre/core/constants/Field.java, backend/src/main/java/fr/openent/mediacentre/service/FavoriteService.java, backend/src/main/java/fr/openent/mediacentre/service/SignetService.java, backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultFavoriteService.java, backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultSignetService.java, backend/src/main/java/fr/openent/mediacentre/source/Moodle.java, frontend/src/core/const/typescript.const.ts, frontend/src/hooks/useResourceListInfo.ts, frontend/src/services/api/signet.service.ts, frontend/src/utils/property.utils.ts
This pull request introduces several changes to improve the update functionality for signets and favorites, as well as some minor enhancements and bug fixes. The most important changes include updating the `SignetService` and `FavoriteService` interfaces, implementing the update method in the `DefaultFavoriteService` class, and adding additional error handling and logging.
* [`backend/src/main/java/fr/openent/mediacentre/controller/SignetController.java`](diffhunk://#diff-7acb496e91725af56430ff95b99b983ba16eb291b292c38364bd5e1917e10798L156-R162): Enhanced the `update` method to update both signet and favorite services and added error handling and logging.
* [`backend/src/main/java/fr/openent/mediacentre/service/FavoriteService.java`](diffhunk://#diff-fc70c00e7cdca2327cabaf96dbd57582281e67b …
=> fix(signet): #MED-375 update favorites when signet is updated

backend/deployment/mediacentre/conf.json.template, backend/src/main/java/fr/openent/mediacentre/controller/MediacentreController.java, backend/src/main/java/fr/openent/mediacentre/core/constants/Field.java, frontend/src/components/pins-carousel/pins-carousel-card/PinsCarouselCard.tsx
This pull request introduces new functionality to handle text highlights pins in both the backend and frontend of the mediacentre application. The most important changes include updates to configuration files, controller logic, constants, and frontend components.
* [`backend/deployment/mediacentre/conf.json.template`](diffhunk://#diff-37db00e5258edab79cacd3beb685d12f5171c21ae4af6137b24132c3f8129f2dR32): Added a new configuration parameter `textHighlightsPins`.
* [`backend/src/main/java/fr/openent/mediacentre/controller/MediacentreController.java`](diffhunk://#diff-a18d1872cf8a18605dcb8e9e9431e0343f96f3b0d1cf0881d2e93613a898ad93L69-R70): Updated the `view` method to include `TEXT_HIGHLIGHTS_PINS` in the response.
* [`backend/src/main/java/fr/openent/mediacentre/core/constants/Field.java`](d …
=> feat(pins): #MED-378 add conf param for highlight text
